### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by brettburwell** [kotyy/craft-eventbrite#2]
Hi there. This plugin looks great. I have an upcoming project that will integrate with Eventbrite. I'm curious if you have any plans to port this plugin to Craft 3 when it comes out?

**Comment by kotyy** [comment]
Thanks. Glad you're getting use out of it.

I haven't worked with Craft 3 yet, but I know the plugin architecture has changed a fair amount. 

Once I've played around with 3 and looked at couple of updated plugins, I figure it will be easy to update this. Biggest question right now is if I can maintain backwards compatibility with Craft 2 or if I'll need a separate branch/project.

Any insight you have is welcome. :)

**Comment by brettburwell** [comment]
Thanks for the reply @kotyy. I'm not really a plugin dev, so I wouldn't have too many insights to offer. But based on what I've read about Craft 3, my guess is backward compatibility might not be possible. 

Either way, I'll keep an eye on the repo. Keep up the good work and thanks for sharing.
